require 'rake'
require 'rake/testtask'
require 'rcov/rcovtask'

task :default => [:unit_test]

desc "Run unit tests"
Rake::TestTask.new("unit_test") { |t|
  t.pattern = 'tc_*.rb'
  t.verbose = true
  t.warning = true
}


desc 'Run unit tests with coverage'
Rcov::RcovTask.new("coverage") do |t|
  t.libs << "test"
  t.pattern = 'tc_*.rb'
  t.output_dir = "coverage"
  t.verbose = true
end
